from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.hosted_zone import HostedZone
    from app.models.record_value import RecordValue

# The nine user-creatable types (FR-D1) plus SOA, generated by the system only (FR-B13, DR-5).
RECORD_TYPES = ("A", "AAAA", "CNAME", "TXT", "MX", "NS", "PTR", "SRV", "CAA", "SOA")


class RecordSet(Base):
    __tablename__ = "record_sets"
    __table_args__ = (
        UniqueConstraint(
            "hosted_zone_id", "name", "type", "set_identifier", name="uq_record_sets_identity"
        ),
        CheckConstraint(
            "type IN (" + ", ".join(f"'{t}'" for t in RECORD_TYPES) + ")", name="ck_record_sets_type"
        ),
        CheckConstraint(
            "ttl IS NULL OR (ttl >= 0 AND ttl <= 2147483647)", name="ck_record_sets_ttl_range"
        ),
        Index("ix_record_sets_zone_type", "hosted_zone_id", "type"),
        Index("ix_record_sets_zone_required", "hosted_zone_id", "is_required"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    record_id: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    hosted_zone_id: Mapped[int] = mapped_column(
        ForeignKey("hosted_zones.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String, nullable=False)
    type: Mapped[str] = mapped_column(String, nullable=False)
    # '' for Simple, never NULL — NULL is distinct in a unique index, so NULL would let
    # duplicate record sets be inserted and break FR-C1 entirely (invariant 4).
    set_identifier: Mapped[str] = mapped_column(String, nullable=False, server_default="")
    routing_policy: Mapped[str] = mapped_column(String, nullable=False, server_default="SIMPLE")
    routing_config: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    alias_target: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    ttl: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_required: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, server_default=func.now(), onupdate=func.now()
    )

    hosted_zone: Mapped["HostedZone"] = relationship(back_populates="record_sets")
    values: Mapped[list["RecordValue"]] = relationship(
        back_populates="record_set",
        passive_deletes=True,
        order_by="RecordValue.ordinal",
    )
