/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hosted Zones */
        get: operations["list_hosted_zones_v1_hosted_zones_get"];
        put?: never;
        /** Create Hosted Zone */
        post: operations["create_hosted_zone_v1_hosted_zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hosted Zone */
        get: operations["get_hosted_zone_v1_hosted_zones__zone_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Hosted Zone */
        patch: operations["update_hosted_zone_v1_hosted_zones__zone_id__patch"];
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Records
         * @description List-only (Slice 3, for the zone detail Records tab / AC-2). Create, update,
         *     delete, and validation are Slice 4 (session C).
         */
        get: operations["list_records_v1_hosted_zones__zone_id__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostedZoneCreate */
        HostedZoneCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @default PUBLIC
             * @enum {string}
             */
            type: "PUBLIC" | "PRIVATE";
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: components["schemas"]["TagInput"][];
        };
        /** HostedZoneDetail */
        HostedZoneDetail: {
            /** Zoneid */
            zoneId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /** Recordcount */
            recordCount: number;
            /** Createdby */
            createdBy: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Nameservers */
            nameServers: string[];
            /** Tags */
            tags: components["schemas"]["TagResponse"][];
        };
        /** HostedZoneListItem */
        HostedZoneListItem: {
            /** Zoneid */
            zoneId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /** Recordcount */
            recordCount: number;
            /** Createdby */
            createdBy: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** HostedZoneUpdate */
        HostedZoneUpdate: {
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: components["schemas"]["TagInput"][] | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Page[HostedZoneListItem] */
        Page_HostedZoneListItem_: {
            /** Items */
            items: components["schemas"]["HostedZoneListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** Page[RecordListItem] */
        Page_RecordListItem_: {
            /** Items */
            items: components["schemas"]["RecordListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** RecordListItem */
        RecordListItem: {
            /** Recordid */
            recordId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Routingpolicy */
            routingPolicy: string;
            /** Setidentifier */
            setIdentifier: string;
            /** Ttl */
            ttl: number | null;
            /** Values */
            values: string[];
            /** Aliastarget */
            aliasTarget: {
                [key: string]: unknown;
            } | null;
            /** Isrequired */
            isRequired: boolean;
        };
        /** TagInput */
        TagInput: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** TagResponse */
        TagResponse: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Displayname */
            displayName: string;
            /** Accountid */
            accountId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_hosted_zones_v1_hosted_zones_get: {
        parameters: {
            query?: {
                search?: string | null;
                type?: ("PUBLIC" | "PRIVATE") | null;
                sort?: "name" | "recordCount" | "type" | "createdAt";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HostedZoneListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hosted_zone_v1_hosted_zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hosted_zone_v1_hosted_zones__zone_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hosted_zone_v1_hosted_zones__zone_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_v1_hosted_zones__zone_id__records_get: {
        parameters: {
            query?: {
                search?: string | null;
                type?: string[] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecordListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
