/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hosted Zones */
        get: operations["list_hosted_zones_v1_hosted_zones_get"];
        put?: never;
        /** Create Hosted Zone */
        post: operations["create_hosted_zone_v1_hosted_zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hosted Zone */
        get: operations["get_hosted_zone_v1_hosted_zones__zone_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Hosted Zone
         * @description FR-B18/FR-B18a: 409 HostedZoneNotEmpty unless `cascade=true`, in which
         *     case every record set, value, and tag is deleted atomically with the zone.
         */
        delete: operations["delete_hosted_zone_v1_hosted_zones__zone_id__delete"];
        options?: never;
        head?: never;
        /** Update Hosted Zone */
        patch: operations["update_hosted_zone_v1_hosted_zones__zone_id__patch"];
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_v1_hosted_zones__zone_id__records_get"];
        put?: never;
        /** Create Record */
        post: operations["create_record_v1_hosted_zones__zone_id__records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record
         * @description Not in the original API contract's endpoint table (which only lists list/
         *     create/update/delete for records) — added because the edit page needs to
         *     fetch one record's current values without paging through the full list.
         */
        get: operations["get_record_v1_hosted_zones__zone_id__records__record_id__get"];
        put?: never;
        post?: never;
        /** Delete Record */
        delete: operations["delete_record_v1_hosted_zones__zone_id__records__record_id__delete"];
        options?: never;
        head?: never;
        /** Update Record */
        patch: operations["update_record_v1_hosted_zones__zone_id__records__record_id__patch"];
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}/records/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Delete Records */
        post: operations["bulk_delete_records_v1_hosted_zones__zone_id__records_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/record-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Record Types
         * @description FR-D6: the single source of truth for all nine grammars, fetched once
         *     and cached by the frontend — no grammar is ever duplicated in TypeScript.
         */
        get: operations["list_record_types_v1_record_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Zone
         * @description FR-G2. BIND output must re-import cleanly into an empty zone and
         *     produce an identical record set — the round-trip guarantee in AC-15.
         */
        get: operations["export_zone_v1_hosted_zones__zone_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/hosted-zones/{zone_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Zone File
         * @description FR-G3. `dry_run=true` always returns a preview and writes nothing;
         *     committing with any `rejected` entry returns 422 and creates nothing —
         *     import is all-or-nothing.
         */
        post: operations["import_zone_file_v1_hosted_zones__zone_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkDeleteRequest */
        BulkDeleteRequest: {
            /** Recordids */
            recordIds: string[];
        };
        /**
         * ChangeInfo
         * @description Mocked change object every record mutation and zone create returns,
         *     matching Route53's response shape (FR-C17, 06-api-contract.md §7).
         */
        ChangeInfo: {
            /** Id */
            id: string;
            /**
             * Status
             * @default INSYNC
             */
            status: string;
            /**
             * Submittedat
             * Format: date-time
             */
            submittedAt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HostedZoneCreate */
        HostedZoneCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @default PUBLIC
             * @enum {string}
             */
            type: "PUBLIC" | "PRIVATE";
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: components["schemas"]["TagInput"][];
        };
        /** HostedZoneCreateResponse */
        HostedZoneCreateResponse: {
            /** Zoneid */
            zoneId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /** Recordcount */
            recordCount: number;
            /** Createdby */
            createdBy: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Nameservers */
            nameServers: string[];
            /** Tags */
            tags: components["schemas"]["TagResponse"][];
            changeInfo: components["schemas"]["ChangeInfo"];
        };
        /** HostedZoneDetail */
        HostedZoneDetail: {
            /** Zoneid */
            zoneId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /** Recordcount */
            recordCount: number;
            /** Createdby */
            createdBy: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Nameservers */
            nameServers: string[];
            /** Tags */
            tags: components["schemas"]["TagResponse"][];
        };
        /** HostedZoneListItem */
        HostedZoneListItem: {
            /** Zoneid */
            zoneId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string | null;
            /** Recordcount */
            recordCount: number;
            /** Createdby */
            createdBy: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** HostedZoneUpdate */
        HostedZoneUpdate: {
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: components["schemas"]["TagInput"][] | null;
        };
        /**
         * ImportContentBody
         * @description Pasted-text alternative to a multipart file upload (06-api-contract.md §6).
         */
        ImportContentBody: {
            /** Content */
            content: string;
        };
        /** ImportCreateItem */
        ImportCreateItem: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Ttl */
            ttl: number | null;
            /** Values */
            values: string[];
        };
        /** ImportPreviewResponse */
        ImportPreviewResponse: {
            /** Tocreate */
            toCreate: components["schemas"]["ImportCreateItem"][];
            /** Skipped */
            skipped: components["schemas"]["ImportSkippedItem"][];
            /** Rejected */
            rejected: components["schemas"]["ImportRejectedItem"][];
        };
        /** ImportRejectedItem */
        ImportRejectedItem: {
            /** Line */
            line: number;
            /** Raw */
            raw: string;
            /** Reason */
            reason: string;
        };
        /** ImportSkippedItem */
        ImportSkippedItem: {
            /** Line */
            line: number;
            /** Reason */
            reason: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** Page[HostedZoneListItem] */
        Page_HostedZoneListItem_: {
            /** Items */
            items: components["schemas"]["HostedZoneListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** Page[RecordListItem] */
        Page_RecordListItem_: {
            /** Items */
            items: components["schemas"]["RecordListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** RecordCreate */
        RecordCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "A" | "AAAA" | "CNAME" | "TXT" | "MX" | "NS" | "PTR" | "SRV" | "CAA";
            /** Ttl */
            ttl?: number | null;
            /** Values */
            values?: string[];
            /**
             * Routingpolicy
             * @default SIMPLE
             */
            routingPolicy: string;
            /**
             * Setidentifier
             * @default
             */
            setIdentifier: string;
            /** Routingconfig */
            routingConfig?: {
                [key: string]: unknown;
            } | null;
            /** Aliastarget */
            aliasTarget?: {
                [key: string]: unknown;
            } | null;
        };
        /** RecordListItem */
        RecordListItem: {
            /** Recordid */
            recordId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Routingpolicy */
            routingPolicy: string;
            /** Setidentifier */
            setIdentifier: string;
            /** Ttl */
            ttl: number | null;
            /** Values */
            values: string[];
            /** Aliastarget */
            aliasTarget: {
                [key: string]: unknown;
            } | null;
            /** Isrequired */
            isRequired: boolean;
        };
        /** RecordMutationResponse */
        RecordMutationResponse: {
            /** Recordid */
            recordId: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Routingpolicy */
            routingPolicy: string;
            /** Setidentifier */
            setIdentifier: string;
            /** Ttl */
            ttl: number | null;
            /** Values */
            values: string[];
            /** Aliastarget */
            aliasTarget: {
                [key: string]: unknown;
            } | null;
            /** Isrequired */
            isRequired: boolean;
            changeInfo: components["schemas"]["ChangeInfo"];
        };
        /** RecordTypeMetadata */
        RecordTypeMetadata: {
            /** Type */
            type: string;
            /** Pattern */
            pattern: string;
            /** Placeholder */
            placeholder: string;
            /** Helptext */
            helpText: string;
            /** Multivalue */
            multiValue: boolean;
            /** Maxvalues */
            maxValues: number;
            /** Maxvaluelength */
            maxValueLength: number;
            /** Requiresttl */
            requiresTtl: boolean;
        };
        /** RecordTypesResponse */
        RecordTypesResponse: {
            /** Items */
            items: components["schemas"]["RecordTypeMetadata"][];
        };
        /** RecordUpdate */
        RecordUpdate: {
            /** Values */
            values?: string[] | null;
            /** Ttl */
            ttl?: number | null;
            /** Routingpolicy */
            routingPolicy?: string | null;
            /** Routingconfig */
            routingConfig?: {
                [key: string]: unknown;
            } | null;
            /** Aliastarget */
            aliasTarget?: {
                [key: string]: unknown;
            } | null;
        };
        /** TagInput */
        TagInput: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** TagResponse */
        TagResponse: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Displayname */
            displayName: string;
            /** Accountid */
            accountId: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_hosted_zones_v1_hosted_zones_get: {
        parameters: {
            query?: {
                search?: string | null;
                type?: ("PUBLIC" | "PRIVATE") | null;
                sort?: "name" | "recordCount" | "type" | "createdAt";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HostedZoneListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hosted_zone_v1_hosted_zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hosted_zone_v1_hosted_zones__zone_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_hosted_zone_v1_hosted_zones__zone_id__delete: {
        parameters: {
            query?: {
                cascade?: boolean;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hosted_zone_v1_hosted_zones__zone_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HostedZoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostedZoneDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_v1_hosted_zones__zone_id__records_get: {
        parameters: {
            query?: {
                search?: string | null;
                type?: string[] | null;
                routing_policy?: string | null;
                alias?: boolean | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecordListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_record_v1_hosted_zones__zone_id__records_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_v1_hosted_zones__zone_id__records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordListItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_record_v1_hosted_zones__zone_id__records__record_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_record_v1_hosted_zones__zone_id__records__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_records_v1_hosted_zones__zone_id__records_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_record_types_v1_record_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordTypesResponse"];
                };
            };
        };
    };
    export_zone_v1_hosted_zones__zone_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_zone_file_v1_hosted_zones__zone_id__import_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportContentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
