"""initial

Revision ID: 0001
Revises:
Create Date: 2026-07-27 10:36:05.363113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hosted_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name_servers', sa.JSON(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('PUBLIC', 'PRIVATE')", name='ck_hosted_zones_type'),
    sa.CheckConstraint('description IS NULL OR length(description) <= 256', name='ck_hosted_zones_description_length'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('zone_id')
    )
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.create_index('ix_hosted_zones_type', ['type'], unique=False)

    op.create_table('hosted_zone_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hosted_zone_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hosted_zone_id', 'key', name='uq_hosted_zone_tags_key')
    )
    op.create_table('record_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('hosted_zone_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('set_identifier', sa.String(), server_default='', nullable=False),
    sa.Column('routing_policy', sa.String(), server_default='SIMPLE', nullable=False),
    sa.Column('routing_config', sa.JSON(), nullable=True),
    sa.Column('alias_target', sa.JSON(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('A', 'AAAA', 'CNAME', 'TXT', 'MX', 'NS', 'PTR', 'SRV', 'CAA', 'SOA')", name='ck_record_sets_type'),
    sa.CheckConstraint('ttl IS NULL OR (ttl >= 0 AND ttl <= 2147483647)', name='ck_record_sets_ttl_range'),
    sa.ForeignKeyConstraint(['hosted_zone_id'], ['hosted_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hosted_zone_id', 'name', 'type', 'set_identifier', name='uq_record_sets_identity'),
    sa.UniqueConstraint('record_id')
    )
    with op.batch_alter_table('record_sets', schema=None) as batch_op:
        batch_op.create_index('ix_record_sets_zone_required', ['hosted_zone_id', 'is_required'], unique=False)
        batch_op.create_index('ix_record_sets_zone_type', ['hosted_zone_id', 'type'], unique=False)

    op.create_table('record_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_set_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(value) <= 4000', name='ck_record_values_length'),
    sa.ForeignKeyConstraint(['record_set_id'], ['record_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_set_id', 'ordinal', name='uq_record_values_ordinal')
    )
    with op.batch_alter_table('record_values', schema=None) as batch_op:
        batch_op.create_index('ix_record_values_value', ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record_values', schema=None) as batch_op:
        batch_op.drop_index('ix_record_values_value')

    op.drop_table('record_values')
    with op.batch_alter_table('record_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_record_sets_zone_type')
        batch_op.drop_index('ix_record_sets_zone_required')

    op.drop_table('record_sets')
    op.drop_table('hosted_zone_tags')
    with op.batch_alter_table('hosted_zones', schema=None) as batch_op:
        batch_op.drop_index('ix_hosted_zones_type')

    op.drop_table('hosted_zones')
    op.drop_table('users')
    # ### end Alembic commands ###
