from typing import Literal

from pydantic import ConfigDict, Field

from app.schemas.common import CamelModel, ChangeInfo

# SOA excluded — generated by the system at zone creation, never user-creatable (FR-B13).
USER_CREATABLE_TYPES = Literal["A", "AAAA", "CNAME", "TXT", "MX", "NS", "PTR", "SRV", "CAA"]


class RecordListItem(CamelModel):
    record_id: str
    name: str
    type: str
    routing_policy: str
    set_identifier: str
    ttl: int | None
    values: list[str]
    alias_target: dict | None
    is_required: bool


class RecordCreate(CamelModel):
    name: str
    type: USER_CREATABLE_TYPES
    ttl: int | None = None
    values: list[str] = Field(default_factory=list)
    routing_policy: str = "SIMPLE"
    set_identifier: str = ""
    routing_config: dict | None = None
    alias_target: dict | None = None


class RecordUpdate(CamelModel):
    # extra="forbid": name/type are the record's identity (FR-C14) — rejected
    # rather than silently ignored, same pattern as HostedZoneUpdate. Pydantic v2
    # merges this with CamelModel's inherited config, so alias_generator etc. stay.
    model_config = ConfigDict(extra="forbid")

    values: list[str] | None = None
    ttl: int | None = None
    routing_policy: str | None = None
    routing_config: dict | None = None
    alias_target: dict | None = None


class RecordMutationResponse(RecordListItem):
    change_info: ChangeInfo
